in_amounts = [0, 0]
in_enabled = [false, false]
in_indices = [0, 0]
in_paths = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
in_salts = [0, 0]
merkle_root = 0
new_commitments = [0, 0]
nullifiers = [0, 0]
out_amounts = [0, 0]
out_enabled = [false, false]
out_pubkeys = [0, 0]
out_salts = [0, 0]
public_amount = 0
recipient = 0
spending_privkey = 0
token = 0
